---
- name: Deploy Nginx and Sample Project
  hosts: all
  become: yes
  vars:
    project_url: "https://www.tooplate.com/download/2107_new_spot"
    project_zip: "/tmp/project.zip"
    project_dir: "/tmp/project"
    web_root: "/var/www/html"

  tasks:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Install Nginx on Debian family
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Nginx on RedHat family
      ansible.builtin.yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start and enable Nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Ensure unzip is installed (Debian)
      ansible.builtin.apt:
        name: unzip
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Ensure unzip is installed (RedHat)
      ansible.builtin.yum:
        name: unzip
        state: present
      when: ansible_os_family == "RedHat"

    - name: Download sample project zip file
      ansible.builtin.get_url:
        url: "{{ project_url }}"
        dest: "{{ project_zip }}"
        mode: '0644'

    - name: Create project extraction directory
      ansible.builtin.file:
        path: "{{ project_dir }}"
        state: directory
        mode: '0755'

    - name: Unzip project files
      ansible.builtin.unarchive:
        src: "{{ project_zip }}"
        dest: "{{ project_dir }}"
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Copy project files (contents of 2107_new_spot) to web root recursively
      ansible.builtin.command:
        cmd: >
          rsync -a --delete {{ project_dir }}/2107_new_spot/ {{ web_root }}/
      become: yes

    - name: Set ownership and permissions of web root files
      ansible.builtin.file:
        path: "{{ web_root }}"
        recurse: yes
        owner: "{{ 'www-data' if ansible_os_family == 'Debian' else 'nginx' }}"
        group: "{{ 'www-data' if ansible_os_family == 'Debian' else 'nginx' }}"
        mode: '0755'

    - name: Reload Nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
